# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
joint_limits:
  joint1:
    has_position_limits: true
    min_position: -3.15
    max_position: 3.15
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0

  joint2:
    has_position_limits: true
    min_position: -1.58
    max_position: 1.58
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0

  joint3:
    has_position_limits: true
    min_position: -1.58
    max_position: 1.58
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0

  joint4:
    has_position_limits: true
    min_position: -3.15
    max_position: 3.15
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0

  joint5:
    has_position_limits: true
    min_position: -1.58
    max_position: 1.58
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0

  gripper:
    has_position_limits: true
    min_position: -65.5269905 # Gripper Multiplier
    max_position: 94.98867187
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0